"""
LLM-based automatic interpretation of SAE features.
Reads feature activation mapping reports and asks an LLM (e.g. OpenAI GPT-4o-mini or Groq)
to explain what the feature activates on.

Supports any OpenAI-compatible API endpoint (OpenAI, Groq, etc.) via the `base_url` parameter.
Includes retry logic with exponential backoff to gracefully handle TPM rate limits.
"""

import json
import logging
import time
from pathlib import Path
from typing import List, Dict, Any, Optional

try:
    import pandas as pd
except ImportError:
    pass

try:
    from openai import OpenAI
except ImportError:
    pass


logger = logging.getLogger("rfm.analysis.autointerp")

# Default Groq base URL for the openai-compatible endpoint
GROQ_BASE_URL = "https://api.groq.com/openai/v1"


class FeatureAutoInterp:
    def __init__(
        self,
        events_csv_path: str | Path,
        backend: str = "openai",
        api_key: str = None,
        base_url: str = None,
        request_delay: float = 0.0,
        max_retries: int = 5,
        retry_base_delay: float = 10.0,
        system_prompt: str = None,
    ):
        """
        Args:
            events_csv_path: Path to the feature_events.csv generated by `mapping.py`.
            backend: LLM backend to use. Use "openai" for OpenAI or any OpenAI-compatible API
                     (e.g. Groq). The ``base_url`` param controls the actual endpoint.
            api_key: Optional API key. If None, read from the environment.
            base_url: Optional base URL to override the default OpenAI endpoint.
                      Use ``GROQ_BASE_URL`` (https://api.groq.com/openai/v1) for Groq.
            request_delay: Seconds to wait between successive LLM calls (helps avoid TPM limits).
            max_retries: Maximum number of retries on rate-limit (429) errors.
            retry_base_delay: Base delay in seconds for the first retry; doubles on each attempt.
            system_prompt: Custom system prompt for the LLM. Defaults to a standard AI
                           interpretability researcher prompt. Use a safety-focused prompt
                           when analyzing models for harmful content detection.
        """
        self.events_csv_path = Path(events_csv_path)
        self.backend = backend.lower()
        self.api_key = api_key
        self.base_url = base_url
        self.request_delay = request_delay
        self.max_retries = max_retries
        self.retry_base_delay = retry_base_delay
        self.system_prompt = system_prompt or "You are an AI interpretability researcher."
        self.client = None

        if self.backend not in ("openai",):
            raise ValueError(f"Unsupported backend: {backend}. Use 'openai' (also works for Groq via base_url).")

        self._load_events()

    def _get_client(self):
        if self.client is not None:
            return self.client
        try:
            kwargs = {"api_key": self.api_key}
            if self.base_url:
                kwargs["base_url"] = self.base_url
            self.client = OpenAI(**kwargs)
        except NameError:
            raise ImportError("openai package is required. Install it with `pip install openai`.")
        return self.client

    def _load_events(self):
        """Load context events from CSV."""
        if not self.events_csv_path.exists():
            raise FileNotFoundError(f"Events CSV not found: {self.events_csv_path}")

        try:
            df = pd.read_csv(self.events_csv_path)
        except NameError:
             raise ImportError("pandas package is required for feature interpretation. Install it with `pip install pandas`.")

        activation_col = "activation" if "activation" in df.columns else "strength" if "strength" in df.columns else None
        context_col = "context" if "context" in df.columns else "prompt_preview" if "prompt_preview" in df.columns else None

        missing = []
        if "feature_id" not in df.columns:
            missing.append("feature_id")
        if "token_str" not in df.columns:
            missing.append("token_str")
        if activation_col is None:
            missing.append("activation/strength")
        if context_col is None:
            missing.append("context/prompt_preview")
        if missing:
            raise ValueError(
                f"Events CSV at {self.events_csv_path} is missing required columns: {', '.join(missing)}"
            )

        # Normalize legacy and current schemas to a single internal format.
        self.df = df[["feature_id", "token_str", activation_col, context_col]].rename(
            columns={activation_col: "activation", context_col: "context"}
        )

    def get_top_contexts(self, feature_id: int, top_k: int = 15) -> List[Dict[str, Any]]:
        """Extract top activating contexts for a specific feature.
        
        Args:
            feature_id: The ID of the SAE feature.
            top_k: Number of highest activation contexts to retrieve.
        """
        # Filter for the feature
        f_df = self.df[self.df["feature_id"] == feature_id]
        
        if len(f_df) == 0:
            return []

        # Sort by activation strength descending
        top_df = f_df.sort_values(by="activation", ascending=False).head(top_k)
        
        contexts = []
        for _, row in top_df.iterrows():
            contexts.append({
                "token": row["token_str"],
                "activation": float(row["activation"]),
                "context": row["context"]
            })
            
        return contexts

    def _build_prompt(self, feature_id: int, contexts: List[Dict[str, Any]]) -> str:
        """Construct prompt for the LLM."""
        prompt = (
            f"You are an expert NLP researcher analyzing the internal representations of a large language model.\n"
            f"I will provide you with a list of text snippets where a specific internal component ('Feature {feature_id}') activated strongly.\n"
            f"For each snippet, I'll show the exact token that triggered the highest activation, the activation strength score, and the surrounding context.\n\n"
            f"Your task is to identify the common pattern, semantic concept, syntactic role, or specific entity that this feature is detecting.\n"
            f"Be concise and specific. Avoid generalizations if the feature detects something narrow (e.g., 'the word \"not\" after a verb' rather than 'negation').\n\n"
            f"Here are the top activating contexts:\n\n"
        )

        for i, ctx in enumerate(contexts, 1):
            prompt += f"Example {i}:\n"
            prompt += f"Target Token: \"{ctx['token']}\"\n"
            prompt += f"Activation Strength: {ctx['activation']:.2f}\n"
            prompt += f"Context: ...{ctx['context']}...\n\n"

        prompt += (
            "Based on these examples, provide a short, 1-3 sentence explanation of what this feature represents.\n"
            "Format your response as a clear, definitive statement. Start your answer with: 'This feature activates on...'"
        )
        return prompt

    def interpret_feature(self, feature_id: int, top_k: int = 15, model: str = "gpt-4o-mini") -> Optional[str]:
        """Use LLM to interpret a single feature with retry on rate-limit errors."""
        contexts = self.get_top_contexts(feature_id, top_k=top_k)
        if not contexts:
            logger.warning(f"No contexts found for Feature {feature_id}. Skipping.")
            return None

        prompt = self._build_prompt(feature_id, contexts)

        delay = self.retry_base_delay
        for attempt in range(self.max_retries + 1):
            try:
                response = self._get_client().chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": self.system_prompt},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.1,
                    max_tokens=150
                )
                return response.choices[0].message.content.strip()
            except Exception as e:
                err_str = str(e)
                is_rate_limit = "429" in err_str or "rate_limit" in err_str.lower()
                if is_rate_limit and attempt < self.max_retries:
                    # Try to parse the suggested retry delay from the error message
                    suggested = None
                    import re
                    match = re.search(r"try again in ([\d.]+)s", err_str)
                    if match:
                        suggested = float(match.group(1)) + 1.0  # add a small buffer
                    wait = suggested if suggested else delay
                    logger.warning(
                        f"Rate limit hit for Feature {feature_id} (attempt {attempt + 1}/{self.max_retries}). "
                        f"Retrying in {wait:.1f}s..."
                    )
                    time.sleep(wait)
                    delay *= 2  # exponential backoff for subsequent retries
                else:
                    logger.error(f"Error calling LLM for Feature {feature_id}: {e}")
                    return None
        return None

    def interpret_features(
        self,
        feature_ids: List[int],
        top_k: int = 15,
        model: str = "gpt-4o-mini",
        existing_results: Optional[Dict] = None,
    ) -> Dict[int, str]:
        """Interpret a list of features **sequentially** with rate-limit awareness.

        Args:
            feature_ids: List of SAE feature IDs to interpret.
            top_k: Number of top activating contexts to pass to the LLM per feature.
            model: LLM model name (e.g. 'llama-3.1-8b-instant' for Groq).
            existing_results: Optional dict of already-computed results to skip (resume support).
        """
        results: Dict[int, str] = dict(existing_results) if existing_results else {}

        pending = [fid for fid in feature_ids if fid not in results]
        skipped = len(feature_ids) - len(pending)
        if skipped:
            logger.info(f"Resuming: skipping {skipped} already-interpreted features.")

        logger.info(f"Interpreting {len(pending)} features sequentially (delay={self.request_delay}s between calls)...")

        for i, fid in enumerate(pending, 1):
            explanation = self.interpret_feature(fid, top_k=top_k, model=model)
            if explanation:
                results[fid] = explanation
                logger.info(f"[{i}/{len(pending)}] Feature {fid}: {explanation[:80]}...")
            else:
                logger.warning(f"[{i}/{len(pending)}] Feature {fid}: no interpretation returned.")

            # Polite delay between requests to stay under TPM limits
            if self.request_delay > 0 and i < len(pending):
                time.sleep(self.request_delay)

        return results

    def save_interpretations(self, interpretations: Dict[int, str], output_path: str | Path):
        """Save text descriptions to JSON."""
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(out_file, "w", encoding="utf-8") as f:
            json.dump(interpretations, f, ensure_ascii=False, indent=2)
        logger.info(f"Saved {len(interpretations)} feature interpretations to {out_file}")
