"""
LLM-based automatic interpretation of SAE features.
Reads feature activation mapping reports and asks an LLM (e.g. OpenAI GPT-4o-mini) to explain what the feature activates on.
"""

import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional

try:
    import pandas as pd
except ImportError:
    pass

try:
    from openai import OpenAI
except ImportError:
    pass


logger = logging.getLogger("rfm.analysis.autointerp")


class FeatureAutoInterp:
    def __init__(self, events_csv_path: str | Path, backend: str = "openai", api_key: str = None):
        """
        Args:
            events_csv_path: Path to the feature_events.csv generated by `mapping.py`.
            backend: LLM backend to use ("openai" supported currently).
            api_key: Optional API key. If None, the backend client will look for it in the environment.
        """
        self.events_csv_path = Path(events_csv_path)
        self.backend = backend.lower()
        self.client = None

        if self.backend == "openai":
            try:
                self.client = OpenAI(api_key=api_key)
            except NameError:
                raise ImportError("openai package is required for the 'openai' backend. Install it with `pip install openai`.")
        else:
            raise ValueError(f"Unsupported backend: {backend}. Use 'openai'.")

        self._load_events()

    def _load_events(self):
        """Load context events from CSV."""
        if not self.events_csv_path.exists():
            raise FileNotFoundError(f"Events CSV not found: {self.events_csv_path}")

        try:
            # We only need specific columns
            self.df = pd.read_csv(
                self.events_csv_path,
                usecols=["feature_id", "token_str", "activation", "context"]
            )
        except NameError:
             raise ImportError("pandas package is required for feature interpretation. Install it with `pip install pandas`.")

    def get_top_contexts(self, feature_id: int, top_k: int = 15) -> List[Dict[str, Any]]:
        """Extract top activating contexts for a specific feature.
        
        Args:
            feature_id: The ID of the SAE feature.
            top_k: Number of highest activation contexts to retrieve.
        """
        # Filter for the feature
        f_df = self.df[self.df["feature_id"] == feature_id]
        
        if len(f_df) == 0:
            return []

        # Sort by activation strength descending
        top_df = f_df.sort_values(by="activation", ascending=False).head(top_k)
        
        contexts = []
        for _, row in top_df.iterrows():
            contexts.append({
                "token": row["token_str"],
                "activation": float(row["activation"]),
                "context": row["context"]
            })
            
        return contexts

    def _build_prompt(self, feature_id: int, contexts: List[Dict[str, Any]]) -> str:
        """Construct prompt for the LLM."""
        prompt = (
            f"You are an expert NLP researcher analyzing the internal representations of a large language model.\n"
            f"I will provide you with a list of text snippets where a specific internal component ('Feature {feature_id}') activated strongly.\n"
            f"For each snippet, I'll show the exact token that triggered the highest activation, the activation strength score, and the surrounding context.\n\n"
            f"Your task is to identify the common pattern, semantic concept, syntactic role, or specific entity that this feature is detecting.\n"
            f"Be concise and specific. Avoid generalizations if the feature detects something narrow (e.g., 'the word \"not\" after a verb' rather than 'negation').\n\n"
            f"Here are the top activating contexts:\n\n"
        )

        for i, ctx in enumerate(contexts, 1):
            prompt += f"Example {i}:\n"
            prompt += f"Target Token: \"{ctx['token']}\"\n"
            prompt += f"Activation Strength: {ctx['activation']:.2f}\n"
            prompt += f"Context: ...{ctx['context']}...\n\n"

        prompt += (
            "Based on these examples, provide a short, 1-3 sentence explanation of what this feature represents.\n"
            "Format your response as a clear, definitive statement. Start your answer with: 'This feature activates on...'"
        )
        return prompt

    def interpret_feature(self, feature_id: int, top_k: int = 15, model: str = "gpt-4o-mini") -> Optional[str]:
        """Use LLM to interpret a single feature."""
        contexts = self.get_top_contexts(feature_id, top_k=top_k)
        if not contexts:
            logger.warning(f"No contexts found for Feature {feature_id}. Skipping.")
            return None

        prompt = self._build_prompt(feature_id, contexts)

        try:
            if self.backend == "openai":
                response = self.client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": "You are an AI interpretability researcher."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.1,
                    max_tokens=150
                )
                return response.choices[0].message.content.strip()
        except Exception as e:
            logger.error(f"Error calling LLM for Feature {feature_id}: {e}")
            return None

    def interpret_features(self, feature_ids: List[int], top_k: int = 15, model: str = "gpt-4o-mini", max_workers: int = 10) -> Dict[int, str]:
        """Interpret a list of features concurrently."""
        import concurrent.futures
        
        results = {}
        logger.info(f"Starting analysis for {len(feature_ids)} features using {max_workers} threads...")
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_to_fid = {
                executor.submit(self.interpret_feature, fid, top_k, model): fid 
                for fid in feature_ids
            }
            
            for future in concurrent.futures.as_completed(future_to_fid):
                fid = future_to_fid[future]
                try:
                    explanation = future.result()
                    if explanation:
                        results[fid] = explanation
                        logger.info(f"Feature {fid}: {explanation}")
                except Exception as exc:
                    logger.error(f"Feature {fid} generated an exception: {exc}")
                    
        return results

    def save_interpretations(self, interpretations: Dict[int, str], output_path: str | Path):
        """Save text descriptions to JSON."""
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(out_file, "w", encoding="utf-8") as f:
            json.dump(interpretations, f, ensure_ascii=False, indent=2)
        logger.info(f"Saved {len(interpretations)} feature interpretations to {out_file}")
